name: Release and Tag Reusable Workflow
on:
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract Maven project version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: project
      
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: Tag commit
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: v${{ steps.project.outputs.version }}

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: v${{ steps.project.outputs.version }}
        name: ${{ steps.date.outputs.date }}
        body: ${{ steps.tag_version.outputs.changelog }}
